//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class expense
    {
        public int id { get; set; }

        public Nullable<int> userid { get; set; }
        [Display(Name = "Expense Date")]
        public string expensedate { get; set; }
        [Display(Name ="Transaction Description")]
        public string transactiondetail { get; set; }
        [Display(Name = "Transaction Type")]
        public string transactiontype { get; set; }
        [Display(Name = "Transaction Amount")]
        public decimal expenseamount { get; set; }
        [Display(Name = "Remaining Amount")]
        public decimal balanceamount { get; set; }
    
        public virtual user user { get; set; }
    }
}
